### ISSUE TITLE
Impossible d'enregistrer plusieurs séquence audio en utilisant la flêches suivantes

### ISSUE THREAD

**Issue by albang** [kaelhem/moiki-vocalizer#1]
Bonjour,
j'ai découvert moiki à travers le projet lunii studio.
Je trouve le projet super intéressant et très bien réalisé en terme interfaces utilisateurs.
sous windows en version Moiki Vocalizer v0.1.0:
J'ai le bug suivant:
Je clique sur la première séquence à enregistrer 
J'enregistre ma première séquence je clique sur start *je parle * puis stop.
Je clique sur la flèche en haut à droite pour passer à la séquence suivante 
J'enregistre la seconde séquence je clique sur start *je parle * puis stop.
et je clique sur fermer.
La première séquence se retrouve avec l'enregistrement de la seconde.
et la seconde ne se retrouve pas enregistrée

**Comment by kaelhem** [comment]
Bonjour,
Effectivement il y a comme un soucis... Je corrigerai ça cette semaine.
En attendant, bien que ce ne soit pas du tout pratique, il est possible de vocaliser les sons sans qu'ils s'écrasent en fermant la popup après chaque enregistrement de séquence.
Merci pour ce retour !

**Comment by kaelhem** [comment]
Corrigé en version 0.1.1
